name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use '20' if you prefer Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the project (if necessary)
        run: npm run build  # Run this command if your project needs a build step

      - name: Start the application
        run: node index.js
        env:
          CUSTOM_ENV_VARIABLE: ${{ secrets.CUSTOM_ENV_VARIABLE }}  # Set any required environment variables here

      - name: Deploy NodeJS app via SSH
        uses: appleboy/ssh-action@v0.1.2  # Ensure this version is compatible with Node.js 22
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p deploy/test
            cd deploy/test

            if [ -d simple-node-app/.git ]; then
              cd simple-node-app
              git pull
            else
              git clone git@github.com:manjulive89/simple-node-app.git
              cd simple-node-app
            fi

            # The deployment script assumes npm install and build are handled here if needed
            pm2 restart app || pm2 start npm --name "app" -- run start
